// frontend-angular/src/app/features/dashboard/dashboard.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from "@angular/common";
import { DashboardService } from "../../core/services/dashboard.service";
import { DashboardMetrics } from "../../core/models/lead.model";


@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.css'
})
export class DashboardComponent implements OnInit {
  private dashboardService = inject(DashboardService);

  metrics = signal<DashboardMetrics | null>(null);
  isLoading = signal(true);
  isError = signal(false);

  ngOnInit(){
      this.loadMetrics();
  }

  loadMetrics(){
    this.isLoading.set(true);
    this.isError.set(false);

    this.dashboardService.getMetrics().subscribe({
      next: (data) => {
        this.metrics.set(data);
        this.isLoading.set(false);
      },
      error: () => {
        this.isError.set(true);
        this.isLoading.set(false);
      }
    })
  }

  formatCurrency(value: number): string {
    return new Intl.NumberFormat("pt-BR", {
      style:"currency",
      currency:"BRL",
    }).format(value)
  }
}

<div class="p-8">
  <h1 class="text-2xl font-semibold text-gray-900 mb-6">Dashboard</h1>

  @if (metrics(); as m){
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <p class="text-sm text-gray-500 mb-1">Total de Leads</p>
        <p class="text-2xl font-semibold text-gray-900">{{m.totalLeads}}</p>
      </div>
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <p class="text-sm text-gray-500 mb-1">Leads em Negociação</p>
        <p class="text-2xl font-semibold text-gray-900">{{m.leadsEmNegociacao}}</p>
      </div>
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <p class="text-sm text-gray-500 mb-1">Leads Fechados</p>
        <p class="text-2xl font-semibold text-gray-900">{{m.leadsFechados}}</p>
      </div>
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <p class="text-sm text-gray-500 mb-1">Taxa de Conversão</p>
        <p class="text-2xl font-semibold text-gray-900">{{m.taxaConversao}}</p>
      </div>
    </div>

  } @else if (isLoading()){
     <p class="text-gray-500">Carregando métricas...</p>

  } @else  if (isError()){
    <p class="text-red-600">Não foi possível carregar as métricas.</p>
  }
</div>

// frontend-react/app/dashboard/page.tsx
"use client";

import { useMetrics } from "@/src/hooks/useMetrics";

function formatCurrency(value: number){
    return new Intl.NumberFormat("pt-br", {
        style:"currency",
        currency: "BRL",
    }).format(value);
}


export default function DashboardPage(){
    const { metrics, isLoading, isError } = useMetrics(); 

    if(isLoading){
        return <div className="p-8  text-gray-500">Carregando métricas...</div>
    }

    if (isError || !metrics){
        return (
            <div className="p-8 text-red-600">
                Não foi possível carregar as métricas. Tente novamente.
            </div>
        );
    }

    const cards = [
        {
            label:"Total de Leads",
            value: metrics.totalLeads,
        },
        {
            label:"Valor em Negociação",
            value: formatCurrency(metrics.valorEmNegociacao),
        },
        {
            label:"Leads em Negociação",
            value: metrics.leadsEmNegociacao,
        },
        {
            label:"Leads Fechados",
            value: metrics.leadsFechados,
        },
        {
            label:"Taxa de Conversão",
            value: `${metrics.taxaConversao}%`,
        },
    ];
     return (
        <div className="p-8">
            <h1 className="text-2xl font-semibold text-gray-900 mb-6">Dashboard</h1>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                {cards.map((card) => (
                    <div
                    key={card.label}
                    className="bg-white rounded-lg shadow-sm border border-gray-200 p-6"
                    >
                        <p className="text-sm text-gray-500 mb-1">{card.label}</p>
                        <p className="text-2xl font-semibold text-gray-900">{card.value}</p>
                    </div>
                ))}
            </div>
        </div>
    )
}
