// frontend-react/src/components/LeadForm.tsx
"use client";

import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {z} from "zod"
import { Lead, LeadStatus } from "../types";

const leadFormSchema = z.object({
    name: z.string().min(2, "Nome muito curto"),
    company: z.string().min(2, "Empresa muito curta"),
    status: z.enum(["NOVO", "CONTATADO", "NEGOCIANDO", "FECHADO", "PERDIDO"]),
    estimatedValue: z.coerce.number().nonnegative("Valor não pode ser negativo"),
});

type LeadFormInput = z.input<typeof leadFormSchema>;
export type LeadFormData = z.output<typeof leadFormSchema>;

interface LeadFormProps {
    defaultValues?: Partial<Lead>;
    onSubmit: (data: LeadFormData) => Promise<void>;
    submitLabel?: string;
}

const statusOption : {value : LeadStatus, label: string}[] = [
    {value:"NOVO", label:"Novo"},
    {value:"CONTATADO", label:"Contatado"},
    {value:"NEGOCIANDO", label:"Negociando"},
    {value:"FECHADO", label:"Fechado"},
    {value:"PERDIDO", label:"Perdido"}
];

export function LeadForm ({ defaultValues, onSubmit, submitLabel = "Salver"}: LeadFormProps){
    const {
        register,
        handleSubmit,
        formState: {errors, isSubmitting},
    } = useForm<LeadFormInput, any, LeadFormData>({
        resolver: zodResolver(leadFormSchema),
        defaultValues:{
            name: defaultValues?.name ?? "",
            company: defaultValues?.company ?? "",
            status: defaultValues?.status ?? "NOVO",
            estimatedValue: defaultValues?.estimatedValue ?? 0,
        }
    });

    return (
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4 max-w-md">
            <div>
                <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1">
                    Nome do lead
                </label>
                <input
                    id="name"
                    type="text"
                    {...register("name")}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
                {errors.name && <p className="text-sm text-red-600 mt-1">{errors.name.message}</p>}
            </div>

             <div>
                <label htmlFor="company" className="block text-sm font-medium text-gray-700 mb-1">
                    Empresa
                </label>
                <input
                    id="company"
                    type="text"
                    {...register("company")}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
                {errors.company && <p className="text-sm text-red-600 mt-1">{errors.company.message}</p>}
            </div>

            <div>
                <label htmlFor="status" className="block text-sm font-medium text-gray-700 mb-1">
                    Status
                </label>
                <select
                    id="status"
                    {...register("status")}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                {statusOption.map((option) => (
                    <option key={option.value} value={option.value}>
                        {option.label}
                    </option>
                ))}
                </select>
                {errors.status && <p className="text-sm text-red-600 mt-1">{errors.status.message}</p>}
            </div>

            <div>
                <label htmlFor="estimatedValue" className="block text-sm font-medium text-gray-700 mb-1">
                    Valor estimado (R$)
                </label>
                <input
                    id="estimatedValue"
                    type="number"
                    step="0.01"
                    {...register("estimatedValue")}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 "
                />
                {errors.estimatedValue && (
                    <p className="text-sm text-red-600 mt-1">{errors.estimatedValue.message}</p>
                )}
            </div>
            <button
                type="submit"
                disabled={isSubmitting}
                className="w-full bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700 disabled::opacity-50 transition">
                {isSubmitting ? "Salvando.." : submitLabel}
            </button>
        </form>
    )
}

// frontend-angular/src/app/shared/lead-form/lead-form.component.ts
import { Component, EventEmitter, Input, Output, OnInit, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import { ReactiveFormsModule, FormBuilder, Validators, FormsModule } from "@angular/forms";
import { Lead, LeadStatus } from "../../core/models/lead.model";

@Component({
  selector: 'app-lead-form',
  standalone: true,
  imports: [CommonModule,FormsModule, ReactiveFormsModule],
  templateUrl: './lead-form.component.html',
  styleUrl: './lead-form.component.css'
})
export class LeadFormComponent {
private fb = inject(FormBuilder);

@Input() defaultValues: Partial<Lead> | null = null;
@Input() submitLabel = "Salvar"
@Input() isSubmitting = false;
@Output() formSubmit = new EventEmitter<Partial<Lead>>();

 statusOptions: { value: LeadStatus; label: string }[] = [
    { value: "NOVO", label: "Novo" },
    { value: "CONTATADO", label: "Contatado" },
    { value: "NEGOCIANDO", label: "Negociando" },
    { value: "FECHADO", label: "Fechado" },
    { value: "PERDIDO", label: "Perdido" },
  ];

  leadForm = this.fb.group({
    name: ["", [Validators.required, Validators.minLength(2)]],
    company: ["", [Validators.required, Validators.minLength(2)]],
    status: ["NOVO" as LeadStatus, [Validators.required]],
    estimatedValue: [0, [Validators.required, Validators.min(0)]]
  });

  ngOnInit(){
    if (this.defaultValues){
      this.leadForm.patchValue({
        name: this.defaultValues.name ?? "",
        company: this.defaultValues.company ?? "",
        status: this.defaultValues.status ?? "NOVO",
        estimatedValue: this.defaultValues.estimatedValue ?? 0,
      })
    }
  }

  onSubmit(){
    if (this.leadForm.invalid){
      this.leadForm.markAllAsTouched();
      return;
    }
    this.formSubmit.emit(this.leadForm.value as Partial<Lead>)
  }

  get name(){
    return this.leadForm.get("name")!;
  }

  get company(){
    return this.leadForm.get("company")!;
  }

  get status(){
    return this.leadForm.get("status")!;
  }
  get estimatedValeu(){
     return this.leadForm.get("estimatedValue")!;
  }
}

<form [formGroup]="leadForm" (ngSubmit)="onSubmit()" class="space-y-4 max-w-md">
<div>
  <label for="name" class="block text-sm font-medium text-gray-700 mb-1">
    Nome do Lead
  </label>
  <input
    id="name"
    type="text"
    formControlName="name"
    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
  />
  @if (name.invalid && name.touched){
    <p class="text-sm text-red-600 mt-1">Nome muito curto</p>
  }
</div>
<div>
  <label for="company" class="block text-sm font-medium text-gray-700 mb-1">
    Empresa
  </label>
  <input
    id="company"
    type="text"
    formControlName="company"
    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
  />
  @if (company.invalid && company.touched){
    <p class="text-sm text-red-600 mt-1">Empresa muito curta</p>
  }
</div>
<div>
  <label for="status" class="block text-sm font-medium text-gray-700 mb-1">
    Status
  </label>
  <select
    id="status"
    formControlName="status"
    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
  >
  @for (option of statusOptions; track option.value){
    <option [value]="option.value">{{option.label}}</option>
  }
  </select>
</div>

<div>
  <label for="estimatedValue" class="block text-sm font-medium text-gray-700 mb-1">
    Valor estimado (R$)
  </label>
  <input
    id="estimatedValue"
    type="number"
    step="0.01"
    formControlName="estimatedValue"
    class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
  />
  @if (estimatedValeu.invalid && estimatedValeu.touched){
    <p class="text-sm text-red-600 mt-1"> Valor não pode ser negativo</p>
  }
</div>
<button
type="submit"
[disabled]="isSubmitting"
class="w-full bg-blue-600 text-white py-2 rounded-md hover:bg-blue-7-- disabled:opacity-50 transition">
{{isSubmitting ? "Salvando..." : submitLabel}}
</button>

</form>
